services:
  db:
    image: postgres:17-alpine
    container_name: musicmakers-db
    environment:
      - POSTGRES_DB=musicmakers_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    networks:
      - musicmakers-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend-springboot/Projeto
    container_name: musicmakers-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicmakers_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - musicmakers-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: musicmakers-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - musicmakers-network
    restart: always

volumes:
  postgres_data_new:

networks:
  musicmakers-network:
