version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000" 
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=music_makers_db
      - DB_PASSWORD=root
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: music_makers_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: