-- 1. Tabela USUARIO (Base para login e dados gerais)
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(50) NOT NULL, -- Ex: 'MUSICO', 'CONTRATANTE', 'ADMIN'
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabela PERFIL_MUSICO (Extensão de Usuario - 1:1)
CREATE TABLE perfil_musico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE, -- Relacionamento 1:1
    instrumentos_principais VARCHAR(255),
    biografia TEXT,
    link_videos TEXT,
    CONSTRAINT fk_perfil_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- 3. Tabela BANDA
CREATE TABLE banda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    genero_musical VARCHAR(100),
    data_formacao DATE,
    descricao TEXT
);

-- 4. Tabela MEMBRO_BANDA (Relacionamento N:N entre Usuario e Banda com atributos extras)
CREATE TABLE membro_banda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    banda_id BIGINT NOT NULL,
    funcao VARCHAR(100), -- Ex: 'Guitarrista', 'Vocalista'
    gestor BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_membro_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_membro_banda FOREIGN KEY (banda_id) REFERENCES banda(id) ON DELETE CASCADE
);

-- 5. Tabela VAGA (Oportunidades criadas pela banda)
CREATE TABLE vaga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banda_id BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    instrumento_necessario VARCHAR(100) NOT NULL,
    descricao TEXT,
    status VARCHAR(50) DEFAULT 'ABERTA', -- Ex: 'ABERTA', 'FECHADA'
    CONSTRAINT fk_vaga_banda FOREIGN KEY (banda_id) REFERENCES banda(id) ON DELETE CASCADE
);

-- 6. Tabela CANDIDATURA (Músicos se candidatando a vagas)
CREATE TABLE candidatura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_musico_id BIGINT NOT NULL,
    vaga_id BIGINT NOT NULL,
    data_candidatura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'PENDENTE', -- Ex: 'PENDENTE', 'APROVADO', 'REJEITADO'
    CONSTRAINT fk_candidatura_musico FOREIGN KEY (perfil_musico_id) REFERENCES perfil_musico(id) ON DELETE CASCADE,
    CONSTRAINT fk_candidatura_vaga FOREIGN KEY (vaga_id) REFERENCES vaga(id) ON DELETE CASCADE
);

-- 7. Tabela FINANCEIRO (Gestão de caixa da banda)
CREATE TABLE financeiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banda_id BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL, -- 'RECEITA' ou 'DESPESA'
    descricao VARCHAR(255),
    valor DECIMAL(10, 2) NOT NULL,
    data_transacao DATE NOT NULL,
    categoria VARCHAR(100),
    CONSTRAINT fk_financeiro_banda FOREIGN KEY (banda_id) REFERENCES banda(id) ON DELETE CASCADE
);

-- 8. Tabela EVENTO (Shows e ensaios)
CREATE TABLE evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banda_id BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL, -- 'SHOW', 'ENSAIO'
    data_hora TIMESTAMP NOT NULL,
    local VARCHAR(255),
    descricao TEXT,
    CONSTRAINT fk_evento_banda FOREIGN KEY (banda_id) REFERENCES banda(id) ON DELETE CASCADE
);

-- 9. Tabela MUSICA (Repertório)
CREATE TABLE musica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    artista_original VARCHAR(255),
    duracao INT -- Duração em segundos
);

-- 10. Tabela AGENDA_MUSICA (Setlist do evento - N:N entre Evento e Musica)
CREATE TABLE agenda_musica (
    evento_id BIGINT NOT NULL,
    musica_id BIGINT NOT NULL,
    ordem_execucao INT,
    PRIMARY KEY (evento_id, musica_id),
    CONSTRAINT fk_agenda_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON DELETE CASCADE,
    CONSTRAINT fk_agenda_musica FOREIGN KEY (musica_id) REFERENCES musica(id) ON DELETE CASCADE
);