-- Tabela CONVITE_BANDA (entidade ConviteBanda) — não existia em nenhuma migration anterior
CREATE TABLE convite_banda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banda_id BIGINT NOT NULL,
    usuario_convidado_id BIGINT NOT NULL,
    usuario_gestor_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    data_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_resposta TIMESTAMP,
    CONSTRAINT fk_convite_banda FOREIGN KEY (banda_id) REFERENCES banda(id) ON DELETE CASCADE,
    CONSTRAINT fk_convite_usuario_convidado FOREIGN KEY (usuario_convidado_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_convite_usuario_gestor FOREIGN KEY (usuario_gestor_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Tabela PERMISSAO_MEMBRO (entidade PermissaoMembro) — não existia em nenhuma migration anterior
CREATE TABLE permissao_membro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membro_banda_id BIGINT NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    permitido BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_permissao_membro FOREIGN KEY (membro_banda_id) REFERENCES membro_banda(id) ON DELETE CASCADE,
    CONSTRAINT uq_permissao_membro_modulo UNIQUE (membro_banda_id, modulo)
);

-- Colunas faltantes em PERFIL_MUSICO (entidade PerfilMusico)
ALTER TABLE perfil_musico
    ADD COLUMN whatsapp VARCHAR(255),
    ADD COLUMN data_nascimento VARCHAR(255);
