-- Tabela PERFIL_GESTOR (Extensão de Usuario - 1:1) para o perfil de Gestor de Banda
CREATE TABLE perfil_gestor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    whatsapp VARCHAR(255),
    estado VARCHAR(100),
    cidade VARCHAR(150),
    nome_produtora VARCHAR(255),
    tempo_experiencia_gestao VARCHAR(50),
    generos_musicais VARCHAR(255),
    bio TEXT,
    links_profissionais TEXT,
    CONSTRAINT fk_perfil_gestor_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);
