spring.datasource.url=jdbc:postgresql://localhost:5432/music_makers_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=rosina.emard72@ethereal.email
spring.mail.password=NdVwpa2AUsNbYuS6ZN
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true