# --- CONFIGURAÇÃO DO BANCO DE DADOS ---
spring.datasource.url=jdbc:postgresql://localhost:5432/music_makers_db
spring.datasource.username=postgres
# Verifique se esta é a senha correta do seu banco de dados PostgreSQL!
spring.datasource.password=root

# --- CONFIGURAÇÃO DO JPA/HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURAÇÃO DE E-MAIL (AMAZON SES SMTP) ---
# DADOS DE PRODUÇÃO (REGIÃO SA-EAST-1 - SÃO PAULO)
spring.mail.host=email-smtp.sa-east-1.amazonaws.com 
spring.mail.port=587
spring.mail.username=AKIATWNIGBVIS2DR3UP5
spring.mail.password=BFZHM86oK+CCbfIYZeTB96A9V9aIBFkR4Q1pThMkbluZ

# --- CONFIGURAÇÕES DE SEGURANÇA (Obrigatórias para SES na porta 587 - STARTTLS) ---
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# --- CONFIGURAÇÃO DE SEGURANÇA (JWT) ---
jwt.secret=R71q3QOgmEboQv0Gogp0siu4OK19UjCErgjDXe8v5d0=