# URL de conexão: indica que estamos usando postgresql, no seu computador (localhost), na porta 5432, e o banco de dados se chama music_makers_db
spring.datasource.url=jdbc:postgresql://localhost:5432/music_makers_db

# Usuário e senha para acessar o banco de dados
spring.datasource.username=user
spring.datasource.password=password

# Dialeto: Ensina o Hibernate a "falar" a versão correta do SQL para o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update: Isso é muito importante! O Hibernate vai olhar para suas classes @Entity
# e criar ou atualizar as tabelas no banco de dados automaticamente quando a aplicação iniciar.
spring.jpa.hibernate.ddl-auto=update

# show-sql=true: Mostra no console todos os comandos SQL que o Hibernate está executando.
# É excelente para você aprender e ver o que está acontecendo por baixo dos panos.
spring.jpa.show-sql=true
